### ISSUE TITLE
Improve loading time.

### ISSUE THREAD

**Issue by phseiff** [phseiff/phseiff.github.io#26]
I should improve the overall loading time of the website. This is not really an issue on its own, but something most other issues work towards. As it is now, gmetrix.com reports 4.8s time to load, which is too much for my liking. I should be able to reduce this to at the most 2 seconds.

**Comment by phseiff** [comment]
The leading time went down from around 23 seconds to around 4 seconds, just by compressing assets and the icon of the website. Further, optimizing the images used in the single essays should significantly reduce this further, but these are (mainly) issues for gh-md-to-html.

**Comment by phseiff** [comment]
Last thing I need to do is automatically generate my icon with Pillow as described [here](https://stackoverflow.com/a/36168447/9816158), and then maybe (!) bake the darkmode generated by DarkReader into the html.

**Comment by phseiff** [comment]
I used [this favicon generator](https://realfavicongenerator.net) instead.

I still need to automate darkreader javascript execution.

**Comment by phseiff** [comment]
I did this by using DarkReader with [this](https://github.com/darkreader/darkreader/pull/3872) PR (not yet part of DarkReader, sadly, but didn't stop me from applying it to a fork), and by using Selenium to extract the generated CSS, and it works great!

I am now down to 2.3 seconds loading time according to gtmetrix.com, and 1.3 seconds according to lighthouse. This, I am satisfied with.

**Comment by Gusted** [comment]
> I did this by using DarkReader with this PR (not yet part of DarkReader, sadly, but didn't stop me from applying it to a fork), and by using Selenium to extract the generated CSS, and it works great!

It's merged and will be included into the API next release(v4.9.22 probably)!

**Comment by phseiff** [comment]
That's great to hear!
