### ISSUE TITLE
Icon (in the title) taking very long to load

### ISSUE THREAD

**Issue by phseiff** [phseiff/phseiff.github.io#3]
The icon in the title has a very high resolution and thus takes very long to load. This should be reduced by reducing the resolution.

**Comment by phseiff** [comment]
Using progressive jpeg and scaling the image down would pretty much be the best way to solve this.

**Comment by tzekid** [comment]
Try [squoosh](https://squoosh.app/)  :man_shrugging: The jpeg at 40% jpeg quality is about 90% smaller

**Comment by phseiff** [comment]
Thanks, I just looked into it and I think I should go with the compression you suggested. I am currently fucusing on increasing my automated review results at woorank.com and other SEO optimizations, and once I'm done with that (should take around 2 days once I find time to continue working on it) I will invest some time into building automated image-, css- and js-compression into my website builder to heavily decrease the size of images based on the context they are used for.

**Comment by phseiff** [comment]
The top icon as well as the icon from the 404 error page are now automatically scaled down and compressed by my website builder, from around 1,5 MB to around 26,4 KB (70% quality; progressive JPEG).

Any loading time issues for the icons should be solved by that.
